### PR TITLE
Update tools versions to build on modern systems.

### PR DESCRIPTION
**Pull request by ioctl-user**
subj

### CODE REVIEW

**Review by tobykurien — COMMENTED** [review]
Thanks, these are still pretty old versions, can we upgrade to even newer versions?

**Comment by ioctl-user** [comment]
I'm really not familiar with the gradle tool.

The only I have tested is set buildToolsVersion to "22.0.1" , in this case project can be build. And cannot be build with version 23.*.* .

**Comment by ioctl-user** [comment]
Add shorter sleep and sync periods.

**Comment by tobykurien** [comment]
Thanks!

**Pull request merged**
